<?php
/**
 * Created by PhpStorm.
 * User: ckogler
 * Date: 22.06.2016
 * Time: 14:16
 */

namespace ProcessManager\Executor;

class ExportToolkit extends AbstractExecutor
{
    protected $name = 'exportToolkit';
    protected $extJsConfigurationClass = 'pimcore.plugin.processmanager.executor.class.exportToolkit';

    public function getCommand()
    {
        $command = \Pimcore\Tool\Console::getPhpCli().' ' . PIMCORE_DOCUMENT_ROOT.'/pimcore/cli/console.php export-toolkit:export --config-name=' . $this->getValues()['configName'];
        return $command;
    }

    public function getConfig()
    {
        $config= parent::getConfig(); // TODO: Change the autogenerated stub
        $config['jobs'] = \ExportToolkit_Configuration::getList();
        return $config;
    }
}